import { Match } from "./types";

export const MATCHES: Match[] = [
  {
    id: "france-argentine",
    homeTeam: {
      id: "france",
      name: "France",
      shortName: "FRA",
      flag: "🇫🇷",
      group: "A",
      fifaRanking: 2,
      coach: "Didier Deschamps",
      recentForm: [
        { opponent: "Espagne", result: "D", score: "1-1", competition: "UEFA Nations League" },
        { opponent: "Belgique", result: "W", score: "3-0", competition: "UEFA Nations League" },
        { opponent: "Italie", result: "W", score: "2-1", competition: "Match amical" },
        { opponent: "Allemagne", result: "W", score: "2-0", competition: "UEFA Nations League" },
        { opponent: "Portugal", result: "D", score: "0-0", competition: "Match amical" },
      ],
      stats: {
        possession: 58,
        goalsScored: 18,
        goalsConceded: 5,
        xGFor: 17.2,
        xGAgainst: 6.1,
        qualificationPath: "Groupe 2 UEFA — 1er (8V 1N 1D)",
        cleanSheets: 5,
      },
      lineup: {
        formation: "4-3-3",
        players: [
          { name: "Maignan", position: "GK", number: 1, flag: "🇫🇷" },
          { name: "Koundé", position: "RB", number: 5, flag: "🇫🇷" },
          { name: "Upamecano", position: "CB", number: 4, flag: "🇫🇷" },
          { name: "Saliba", position: "CB", number: 13, flag: "🇫🇷" },
          { name: "T. Hernandez", position: "LB", number: 22, flag: "🇫🇷" },
          { name: "Tchouaméni", position: "CM", number: 8, flag: "🇫🇷" },
          { name: "Camavinga", position: "CM", number: 14, flag: "🇫🇷" },
          { name: "Rabiot", position: "CM", number: 25, flag: "🇫🇷" },
          { name: "Dembélé", position: "RW", number: 11, flag: "🇫🇷" },
          { name: "Mbappé", position: "ST", number: 10, flag: "🇫🇷" },
          { name: "Griezmann", position: "LW", number: 7, flag: "🇫🇷" },
        ],
      },
      keyPlayers: ["Kylian Mbappé", "Antoine Griezmann", "Ousmane Dembélé"],
      injuries: [],
      suspensions: [],
    },
    awayTeam: {
      id: "argentine",
      name: "Argentine",
      shortName: "ARG",
      flag: "🇦🇷",
      group: "A",
      fifaRanking: 1,
      coach: "Lionel Scaloni",
      recentForm: [
        { opponent: "Uruguay", result: "W", score: "1-0", competition: "CONMEBOL Q." },
        { opponent: "Brésil", result: "W", score: "2-0", competition: "CONMEBOL Q." },
        { opponent: "Colombie", result: "D", score: "1-1", competition: "CONMEBOL Q." },
        { opponent: "Venezuela", result: "W", score: "3-1", competition: "CONMEBOL Q." },
        { opponent: "Bolivie", result: "W", score: "6-0", competition: "CONMEBOL Q." },
      ],
      stats: {
        possession: 54,
        goalsScored: 22,
        goalsConceded: 4,
        xGFor: 20.1,
        xGAgainst: 5.3,
        qualificationPath: "CONMEBOL — 1er (12V 3N 3D)",
        cleanSheets: 7,
      },
      lineup: {
        formation: "4-3-3",
        players: [
          { name: "Dibu Martínez", position: "GK", number: 23, flag: "🇦🇷" },
          { name: "Molina", position: "RB", number: 26, flag: "🇦🇷" },
          { name: "Romero", position: "CB", number: 13, flag: "🇦🇷" },
          { name: "Lisandro M.", position: "CB", number: 14, flag: "🇦🇷" },
          { name: "Acuña", position: "LB", number: 8, flag: "🇦🇷" },
          { name: "De Paul", position: "CM", number: 7, flag: "🇦🇷" },
          { name: "Mac Allister", position: "CM", number: 20, flag: "🇦🇷" },
          { name: "Fernández E.", position: "CM", number: 24, flag: "🇦🇷" },
          { name: "Di María", position: "RW", number: 11, flag: "🇦🇷" },
          { name: "Messi", position: "ST", number: 10, flag: "🇦🇷" },
          { name: "Álvarez J.", position: "LW", number: 9, flag: "🇦🇷" },
        ],
      },
      keyPlayers: ["Lionel Messi", "Ángel Di María", "Rodrigo De Paul"],
      injuries: ["Di María (incertain)"],
      suspensions: [],
    },
    date: "2026-06-14",
    time: "21:00",
    stadium: "MetLife Stadium",
    city: "New York / New Jersey",
    country: "USA",
    group: "A",
    round: "Phase de groupes",
    h2h: [
      { date: "2022-12-18", homeTeam: "Argentine", awayTeam: "France", score: "3-3 (4-2 tab)", competition: "Finale CDM 2022" },
      { date: "2022-11-26", homeTeam: "France", awayTeam: "Argentine", score: "N/A", competition: "CDM 2022 (match différent)" },
      { date: "2018-06-30", homeTeam: "France", awayTeam: "Argentine", score: "4-3", competition: "8e CDM 2018" },
      { date: "2009-06-11", homeTeam: "France", awayTeam: "Argentine", score: "0-2", competition: "Match amical" },
      { date: "2007-11-11", homeTeam: "Argentine", awayTeam: "France", score: "1-0", competition: "Match amical" },
    ],
    odds: [
      { bookmaker: "Winamax", home: 2.85, draw: 3.30, away: 2.40 },
      { bookmaker: "Unibet", home: 2.90, draw: 3.25, away: 2.45 },
      { bookmaker: "PMU", home: 2.80, draw: 3.20, away: 2.50 },
    ],
  },
  {
    id: "bresil-allemagne",
    homeTeam: {
      id: "bresil",
      name: "Brésil",
      shortName: "BRE",
      flag: "🇧🇷",
      group: "B",
      fifaRanking: 5,
      coach: "Dorival Júnior",
      recentForm: [
        { opponent: "Paraguay", result: "W", score: "2-0", competition: "CONMEBOL Q." },
        { opponent: "Chili", result: "W", score: "3-1", competition: "CONMEBOL Q." },
        { opponent: "Pérou", result: "D", score: "0-0", competition: "CONMEBOL Q." },
        { opponent: "Colombie", result: "W", score: "2-1", competition: "CONMEBOL Q." },
        { opponent: "Équateur", result: "W", score: "1-0", competition: "CONMEBOL Q." },
      ],
      stats: {
        possession: 61,
        goalsScored: 16,
        goalsConceded: 6,
        xGFor: 14.8,
        xGAgainst: 7.2,
        qualificationPath: "CONMEBOL — 3e (10V 3N 5D)",
        cleanSheets: 4,
      },
      lineup: {
        formation: "4-2-3-1",
        players: [
          { name: "Alisson", position: "GK", number: 1, flag: "🇧🇷" },
          { name: "Danilo", position: "RB", number: 2, flag: "🇧🇷" },
          { name: "Militão", position: "CB", number: 3, flag: "🇧🇷" },
          { name: "Gabriel M.", position: "CB", number: 4, flag: "🇧🇷" },
          { name: "Renan Lodi", position: "LB", number: 6, flag: "🇧🇷" },
          { name: "Casemiro", position: "CDM", number: 5, flag: "🇧🇷" },
          { name: "Bruno G.", position: "CDM", number: 8, flag: "🇧🇷" },
          { name: "Rodrygo", position: "RAM", number: 11, flag: "🇧🇷" },
          { name: "Paquetá", position: "CAM", number: 10, flag: "🇧🇷" },
          { name: "Raphinha", position: "LAM", number: 22, flag: "🇧🇷" },
          { name: "Vinicius Jr.", position: "ST", number: 7, flag: "🇧🇷" },
        ],
      },
      keyPlayers: ["Vinicius Jr.", "Rodrygo", "Raphinha"],
      injuries: [],
      suspensions: [],
    },
    awayTeam: {
      id: "allemagne",
      name: "Allemagne",
      shortName: "ALL",
      flag: "🇩🇪",
      group: "B",
      fifaRanking: 12,
      coach: "Julian Nagelsmann",
      recentForm: [
        { opponent: "Pays-Bas", result: "W", score: "2-1", competition: "UEFA Q." },
        { opponent: "Hongrie", result: "W", score: "5-0", competition: "UEFA Q." },
        { opponent: "Autriche", result: "D", score: "2-2", competition: "UEFA Q." },
        { opponent: "Bosnie", result: "W", score: "3-0", competition: "UEFA Q." },
        { opponent: "Islande", result: "W", score: "2-0", competition: "UEFA Q." },
      ],
      stats: {
        possession: 59,
        goalsScored: 20,
        goalsConceded: 8,
        xGFor: 18.5,
        xGAgainst: 9.1,
        qualificationPath: "Groupe 3 UEFA — 1er (9V 2N 1D)",
        cleanSheets: 4,
      },
      lineup: {
        formation: "4-2-3-1",
        players: [
          { name: "Neuer", position: "GK", number: 1, flag: "🇩🇪" },
          { name: "Kimmich", position: "RB", number: 6, flag: "🇩🇪" },
          { name: "Rüdiger", position: "CB", number: 2, flag: "🇩🇪" },
          { name: "Tah", position: "CB", number: 4, flag: "🇩🇪" },
          { name: "Raum", position: "LB", number: 3, flag: "🇩🇪" },
          { name: "Goretzka", position: "CDM", number: 8, flag: "🇩🇪" },
          { name: "Andrich", position: "CDM", number: 23, flag: "🇩🇪" },
          { name: "Musiala", position: "RAM", number: 10, flag: "🇩🇪" },
          { name: "Gündogan", position: "CAM", number: 21, flag: "🇩🇪" },
          { name: "Gnabry", position: "LAM", number: 20, flag: "🇩🇪" },
          { name: "Havertz", position: "ST", number: 9, flag: "🇩🇪" },
        ],
      },
      keyPlayers: ["Jamal Musiala", "Ilkay Gündogan", "Kai Havertz"],
      injuries: [],
      suspensions: ["Rüdiger (suspendu 1 match)"],
    },
    date: "2026-06-18",
    time: "18:00",
    stadium: "SoFi Stadium",
    city: "Los Angeles",
    country: "USA",
    group: "B",
    round: "Phase de groupes",
    h2h: [
      { date: "2018-03-27", homeTeam: "Allemagne", awayTeam: "Brésil", score: "0-1", competition: "Match amical" },
      { date: "2014-07-08", homeTeam: "Brésil", awayTeam: "Allemagne", score: "1-7", competition: "Demi-finale CDM 2014" },
      { date: "2011-08-10", homeTeam: "Allemagne", awayTeam: "Brésil", score: "3-2", competition: "Match amical" },
      { date: "2006-06-13", homeTeam: "Allemagne", awayTeam: "Brésil", score: "0-0", competition: "Match amical" },
      { date: "2004-03-31", homeTeam: "Brésil", awayTeam: "Allemagne", score: "2-1", competition: "Match amical" },
    ],
    odds: [
      { bookmaker: "Winamax", home: 2.10, draw: 3.50, away: 3.20 },
      { bookmaker: "Unibet", home: 2.15, draw: 3.40, away: 3.25 },
      { bookmaker: "PMU", home: 2.05, draw: 3.45, away: 3.30 },
    ],
  },
  {
    id: "espagne-angleterre",
    homeTeam: {
      id: "espagne",
      name: "Espagne",
      shortName: "ESP",
      flag: "🇪🇸",
      group: "C",
      fifaRanking: 6,
      coach: "Luis de la Fuente",
      recentForm: [
        { opponent: "France", result: "D", score: "1-1", competition: "UEFA Nations League" },
        { opponent: "Danemark", result: "W", score: "2-1", competition: "UEFA Q." },
        { opponent: "Suisse", result: "W", score: "3-0", competition: "UEFA Q." },
        { opponent: "Turquie", result: "W", score: "1-0", competition: "UEFA Q." },
        { opponent: "Norvège", result: "W", score: "3-0", competition: "UEFA Q." },
      ],
      stats: {
        possession: 65,
        goalsScored: 21,
        goalsConceded: 4,
        xGFor: 19.3,
        xGAgainst: 5.8,
        qualificationPath: "Groupe 5 UEFA — 1er (10V 1N 1D)",
        cleanSheets: 6,
      },
      lineup: {
        formation: "4-3-3",
        players: [
          { name: "Unai Simón", position: "GK", number: 1, flag: "🇪🇸" },
          { name: "Carvajal", position: "RB", number: 2, flag: "🇪🇸" },
          { name: "Le Normand", position: "CB", number: 4, flag: "🇪🇸" },
          { name: "Laporte", position: "CB", number: 14, flag: "🇪🇸" },
          { name: "Cucurella", position: "LB", number: 24, flag: "🇪🇸" },
          { name: "Rodri", position: "CDM", number: 16, flag: "🇪🇸" },
          { name: "Pedri", position: "CM", number: 8, flag: "🇪🇸" },
          { name: "Fabian Ruiz", position: "CM", number: 18, flag: "🇪🇸" },
          { name: "Yamal", position: "RW", number: 19, flag: "🇪🇸" },
          { name: "Morata", position: "ST", number: 7, flag: "🇪🇸" },
          { name: "Williams N.", position: "LW", number: 11, flag: "🇪🇸" },
        ],
      },
      keyPlayers: ["Lamine Yamal", "Pedri", "Rodri"],
      injuries: [],
      suspensions: [],
    },
    awayTeam: {
      id: "angleterre",
      name: "Angleterre",
      shortName: "ANG",
      flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      group: "C",
      fifaRanking: 4,
      coach: "Thomas Tuchel",
      recentForm: [
        { opponent: "Allemagne", result: "W", score: "2-1", competition: "UEFA Nations League" },
        { opponent: "Grèce", result: "W", score: "3-0", competition: "UEFA Q." },
        { opponent: "Finlande", result: "W", score: "2-0", competition: "UEFA Q." },
        { opponent: "Albanie", result: "W", score: "5-0", competition: "UEFA Q." },
        { opponent: "Andorre", result: "W", score: "4-0", competition: "UEFA Q." },
      ],
      stats: {
        possession: 56,
        goalsScored: 25,
        goalsConceded: 5,
        xGFor: 22.1,
        xGAgainst: 6.4,
        qualificationPath: "Groupe 7 UEFA — 1er (10V 1N 1D)",
        cleanSheets: 5,
      },
      lineup: {
        formation: "4-3-3",
        players: [
          { name: "Pickford", position: "GK", number: 1, flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
          { name: "Alexander-Arnold", position: "RB", number: 2, flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
          { name: "Walker", position: "CB", number: 5, flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
          { name: "Maguire", position: "CB", number: 6, flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
          { name: "Shaw", position: "LB", number: 3, flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
          { name: "Rice", position: "CDM", number: 4, flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
          { name: "Bellingham", position: "CM", number: 22, flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
          { name: "Saka", position: "RW", number: 7, flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
          { name: "Kane", position: "ST", number: 9, flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
          { name: "Foden", position: "LW", number: 11, flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
          { name: "Grealish", position: "CAM", number: 10, flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
        ],
      },
      keyPlayers: ["Jude Bellingham", "Harry Kane", "Bukayo Saka"],
      injuries: [],
      suspensions: [],
    },
    date: "2026-06-20",
    time: "21:00",
    stadium: "AT&T Stadium",
    city: "Dallas",
    country: "USA",
    group: "C",
    round: "Phase de groupes",
    h2h: [
      { date: "2024-07-14", homeTeam: "Espagne", awayTeam: "Angleterre", score: "2-1", competition: "Finale Euro 2024" },
      { date: "2022-10-15", homeTeam: "Angleterre", awayTeam: "Espagne", score: "1-2", competition: "UEFA Nations League" },
      { date: "2021-10-12", homeTeam: "Espagne", awayTeam: "Angleterre", score: "2-1", competition: "UEFA Nations League" },
      { date: "2018-11-15", homeTeam: "Espagne", awayTeam: "Angleterre", score: "2-3", competition: "UEFA Nations League" },
      { date: "2016-11-15", homeTeam: "Angleterre", awayTeam: "Espagne", score: "2-2", competition: "Match amical" },
    ],
    odds: [
      { bookmaker: "Winamax", home: 2.40, draw: 3.20, away: 2.90 },
      { bookmaker: "Unibet", home: 2.45, draw: 3.15, away: 2.85 },
      { bookmaker: "PMU", home: 2.35, draw: 3.25, away: 2.95 },
    ],
  },
  {
    id: "portugal-maroc",
    homeTeam: {
      id: "portugal",
      name: "Portugal",
      shortName: "POR",
      flag: "🇵🇹",
      group: "D",
      fifaRanking: 7,
      coach: "Roberto Martínez",
      recentForm: [
        { opponent: "Croatie", result: "W", score: "2-1", competition: "UEFA Q." },
        { opponent: "Slovaquie", result: "W", score: "3-0", competition: "UEFA Q." },
        { opponent: "Pologne", result: "W", score: "3-1", competition: "UEFA Q." },
        { opponent: "Écosse", result: "D", score: "2-2", competition: "UEFA Q." },
        { opponent: "Liechtenstein", result: "W", score: "5-0", competition: "UEFA Q." },
      ],
      stats: {
        possession: 57,
        goalsScored: 28,
        goalsConceded: 7,
        xGFor: 25.2,
        xGAgainst: 7.8,
        qualificationPath: "Groupe 1 UEFA — 1er (10V 2N 0D)",
        cleanSheets: 5,
      },
      lineup: {
        formation: "4-3-3",
        players: [
          { name: "Rui Patrício", position: "GK", number: 1, flag: "🇵🇹" },
          { name: "Cancelo", position: "RB", number: 2, flag: "🇵🇹" },
          { name: "Rúben Dias", position: "CB", number: 3, flag: "🇵🇹" },
          { name: "Gonçalo Inácio", position: "CB", number: 5, flag: "🇵🇹" },
          { name: "Mendes N.", position: "LB", number: 25, flag: "🇵🇹" },
          { name: "Vitinha", position: "CDM", number: 8, flag: "🇵🇹" },
          { name: "Bernardo", position: "CM", number: 10, flag: "🇵🇹" },
          { name: "Bruno F.", position: "CM", number: 8, flag: "🇵🇹" },
          { name: "Pedro Neto", position: "RW", number: 7, flag: "🇵🇹" },
          { name: "Ronaldo", position: "ST", number: 7, flag: "🇵🇹" },
          { name: "Rafael Leão", position: "LW", number: 22, flag: "🇵🇹" },
        ],
      },
      keyPlayers: ["Cristiano Ronaldo", "Bruno Fernandes", "Bernardo Silva"],
      injuries: [],
      suspensions: [],
    },
    awayTeam: {
      id: "maroc",
      name: "Maroc",
      shortName: "MAR",
      flag: "🇲🇦",
      group: "D",
      fifaRanking: 14,
      coach: "Walid Regragui",
      recentForm: [
        { opponent: "Tanzanie", result: "W", score: "4-0", competition: "CAN Q." },
        { opponent: "Zambie", result: "W", score: "3-0", competition: "CAN Q." },
        { opponent: "Congo", result: "D", score: "1-1", competition: "CAN Q." },
        { opponent: "Gabon", result: "W", score: "3-1", competition: "CAN Q." },
        { opponent: "Mauritanie", result: "W", score: "2-0", competition: "CAN Q." },
      ],
      stats: {
        possession: 48,
        goalsScored: 14,
        goalsConceded: 3,
        xGFor: 12.1,
        xGAgainst: 4.2,
        qualificationPath: "Zone Afrique — 1er (6V 1N 1D)",
        cleanSheets: 6,
      },
      lineup: {
        formation: "4-4-2",
        players: [
          { name: "Bono", position: "GK", number: 1, flag: "🇲🇦" },
          { name: "Hakimi", position: "RB", number: 2, flag: "🇲🇦" },
          { name: "Saiss", position: "CB", number: 3, flag: "🇲🇦" },
          { name: "Aguerd", position: "CB", number: 5, flag: "🇲🇦" },
          { name: "Mazraoui", position: "LB", number: 6, flag: "🇲🇦" },
          { name: "Amrabat", position: "CM", number: 4, flag: "🇲🇦" },
          { name: "Ounahi", position: "CM", number: 8, flag: "🇲🇦" },
          { name: "Ziyech", position: "RM", number: 7, flag: "🇲🇦" },
          { name: "Sabiri", position: "LM", number: 14, flag: "🇲🇦" },
          { name: "En-Nesyri", position: "ST", number: 9, flag: "🇲🇦" },
          { name: "Boufal", position: "ST", number: 19, flag: "🇲🇦" },
        ],
      },
      keyPlayers: ["Achraf Hakimi", "Hakim Ziyech", "Youssef En-Nesyri"],
      injuries: [],
      suspensions: [],
    },
    date: "2026-06-22",
    time: "18:00",
    stadium: "Estadio Azteca",
    city: "Mexico City",
    country: "Mexique",
    group: "D",
    round: "Phase de groupes",
    h2h: [
      { date: "2022-12-10", homeTeam: "Maroc", awayTeam: "Portugal", score: "1-0", competition: "Quart CDM 2022" },
      { date: "2019-03-23", homeTeam: "Portugal", awayTeam: "Maroc", score: "2-0", competition: "Match amical" },
      { date: "2018-06-20", homeTeam: "Portugal", awayTeam: "Maroc", score: "1-0", competition: "Phase de groupes CDM 2018" },
      { date: "2014-08-05", homeTeam: "Maroc", awayTeam: "Portugal", score: "0-2", competition: "Match amical" },
      { date: "2006-08-16", homeTeam: "Portugal", awayTeam: "Maroc", score: "1-0", competition: "Match amical" },
    ],
    odds: [
      { bookmaker: "Winamax", home: 1.80, draw: 3.60, away: 4.50 },
      { bookmaker: "Unibet", home: 1.85, draw: 3.55, away: 4.40 },
      { bookmaker: "PMU", home: 1.75, draw: 3.65, away: 4.60 },
    ],
  },
  {
    id: "usa-mexique",
    homeTeam: {
      id: "usa",
      name: "États-Unis",
      shortName: "USA",
      flag: "🇺🇸",
      group: "E",
      fifaRanking: 13,
      coach: "Mauricio Pochettino",
      recentForm: [
        { opponent: "Canada", result: "W", score: "2-0", competition: "CONCACAF Q." },
        { opponent: "Mexique", result: "D", score: "1-1", competition: "CONCACAF Q." },
        { opponent: "Panama", result: "W", score: "3-0", competition: "CONCACAF Q." },
        { opponent: "Costa Rica", result: "W", score: "2-1", competition: "CONCACAF Q." },
        { opponent: "Honduras", result: "W", score: "4-0", competition: "CONCACAF Q." },
      ],
      stats: {
        possession: 52,
        goalsScored: 15,
        goalsConceded: 5,
        xGFor: 13.9,
        xGAgainst: 6.1,
        qualificationPath: "CONCACAF — 1er (8V 2N 2D)",
        cleanSheets: 5,
      },
      lineup: {
        formation: "4-3-3",
        players: [
          { name: "Turner", position: "GK", number: 1, flag: "🇺🇸" },
          { name: "Dest", position: "RB", number: 2, flag: "🇺🇸" },
          { name: "Richards", position: "CB", number: 4, flag: "🇺🇸" },
          { name: "Zimmerman", position: "CB", number: 5, flag: "🇺🇸" },
          { name: "Robinson", position: "LB", number: 3, flag: "🇺🇸" },
          { name: "McKennie", position: "CM", number: 8, flag: "🇺🇸" },
          { name: "Adams T.", position: "CDM", number: 6, flag: "🇺🇸" },
          { name: "Musah", position: "CM", number: 4, flag: "🇺🇸" },
          { name: "Reyna", position: "RW", number: 7, flag: "🇺🇸" },
          { name: "Pulisic", position: "ST", number: 10, flag: "🇺🇸" },
          { name: "Weah T.", position: "LW", number: 11, flag: "🇺🇸" },
        ],
      },
      keyPlayers: ["Christian Pulisic", "Tyler Adams", "Weston McKennie"],
      injuries: [],
      suspensions: [],
    },
    awayTeam: {
      id: "mexique",
      name: "Mexique",
      shortName: "MEX",
      flag: "🇲🇽",
      group: "E",
      fifaRanking: 16,
      coach: "Javier Aguirre",
      recentForm: [
        { opponent: "USA", result: "D", score: "1-1", competition: "CONCACAF Q." },
        { opponent: "Canada", result: "D", score: "0-0", competition: "CONCACAF Q." },
        { opponent: "Guatemala", result: "W", score: "3-0", competition: "CONCACAF Q." },
        { opponent: "Jamaïque", result: "W", score: "2-0", competition: "CONCACAF Q." },
        { opponent: "Trinidad", result: "W", score: "4-1", competition: "CONCACAF Q." },
      ],
      stats: {
        possession: 50,
        goalsScored: 12,
        goalsConceded: 6,
        xGFor: 10.8,
        xGAgainst: 7.3,
        qualificationPath: "CONCACAF — 2e (7V 3N 2D)",
        cleanSheets: 4,
      },
      lineup: {
        formation: "4-2-3-1",
        players: [
          { name: "Ochoa G.", position: "GK", number: 13, flag: "🇲🇽" },
          { name: "Sánchez J.", position: "RB", number: 2, flag: "🇲🇽" },
          { name: "Montes N.", position: "CB", number: 3, flag: "🇲🇽" },
          { name: "Araujo J.", position: "CB", number: 4, flag: "🇲🇽" },
          { name: "Vega H.", position: "LB", number: 16, flag: "🇲🇽" },
          { name: "Herrera H.", position: "CDM", number: 6, flag: "🇲🇽" },
          { name: "Alvarez E.", position: "CDM", number: 8, flag: "🇲🇽" },
          { name: "Antuna U.", position: "RAM", number: 7, flag: "🇲🇽" },
          { name: "Lozano H.", position: "CAM", number: 22, flag: "🇲🇽" },
          { name: "Lainez D.", position: "LAM", number: 11, flag: "🇲🇽" },
          { name: "Jiménez R.", position: "ST", number: 9, flag: "🇲🇽" },
        ],
      },
      keyPlayers: ["Hirving Lozano", "Raúl Jiménez", "Guillermo Ochoa"],
      injuries: [],
      suspensions: [],
    },
    date: "2026-06-25",
    time: "21:00",
    stadium: "Rose Bowl",
    city: "Los Angeles",
    country: "USA",
    group: "E",
    round: "Phase de groupes",
    h2h: [
      { date: "2024-03-23", homeTeam: "USA", awayTeam: "Mexique", score: "2-0", competition: "Match amical" },
      { date: "2023-06-15", homeTeam: "Mexique", awayTeam: "USA", score: "1-3", competition: "CONCACAF Nations League" },
      { date: "2021-11-12", homeTeam: "USA", awayTeam: "Mexique", score: "2-0", competition: "CONCACAF Q." },
      { date: "2019-07-07", homeTeam: "USA", awayTeam: "Mexique", score: "1-0", competition: "CONCACAF Gold Cup" },
      { date: "2019-06-26", homeTeam: "Mexique", awayTeam: "USA", score: "1-0", competition: "CONCACAF Gold Cup" },
    ],
    odds: [
      { bookmaker: "Winamax", home: 2.20, draw: 3.10, away: 3.40 },
      { bookmaker: "Unibet", home: 2.25, draw: 3.05, away: 3.35 },
      { bookmaker: "PMU", home: 2.15, draw: 3.15, away: 3.50 },
    ],
  },
  {
    id: "senegal-pays-bas",
    homeTeam: {
      id: "senegal",
      name: "Sénégal",
      shortName: "SEN",
      flag: "🇸🇳",
      group: "F",
      fifaRanking: 18,
      coach: "Aliou Cissé",
      recentForm: [
        { opponent: "Côte d'Ivoire", result: "W", score: "2-0", competition: "CAN Q." },
        { opponent: "Guinée", result: "W", score: "3-1", competition: "CAN Q." },
        { opponent: "Congo", result: "D", score: "1-1", competition: "CAN Q." },
        { opponent: "Mozambique", result: "W", score: "3-0", competition: "CAN Q." },
        { opponent: "Rwanda", result: "W", score: "5-0", competition: "CAN Q." },
      ],
      stats: {
        possession: 50,
        goalsScored: 15,
        goalsConceded: 4,
        xGFor: 13.5,
        xGAgainst: 5.1,
        qualificationPath: "Zone Afrique — 1er (6V 2N 0D)",
        cleanSheets: 5,
      },
      lineup: {
        formation: "4-3-3",
        players: [
          { name: "E. Mendy", position: "GK", number: 16, flag: "🇸🇳" },
          { name: "Sabaly", position: "RB", number: 2, flag: "🇸🇳" },
          { name: "Koulibaly", position: "CB", number: 3, flag: "🇸🇳" },
          { name: "Diallo", position: "CB", number: 4, flag: "🇸🇳" },
          { name: "A. Diallo", position: "LB", number: 5, flag: "🇸🇳" },
          { name: "Gueye I.", position: "CDM", number: 6, flag: "🇸🇳" },
          { name: "Kouyaté", position: "CM", number: 8, flag: "🇸🇳" },
          { name: "Gueye P.", position: "CM", number: 15, flag: "🇸🇳" },
          { name: "Sarr I.", position: "RW", number: 7, flag: "🇸🇳" },
          { name: "Mané S.", position: "ST", number: 10, flag: "🇸🇳" },
          { name: "Diatta O.", position: "LW", number: 11, flag: "🇸🇳" },
        ],
      },
      keyPlayers: ["Sadio Mané", "Kalidou Koulibaly", "Ismaïla Sarr"],
      injuries: ["Mané (incertain)"],
      suspensions: [],
    },
    awayTeam: {
      id: "pays-bas",
      name: "Pays-Bas",
      shortName: "NED",
      flag: "🇳🇱",
      group: "F",
      fifaRanking: 8,
      coach: "Ronald Koeman",
      recentForm: [
        { opponent: "Hongrie", result: "W", score: "4-0", competition: "UEFA Q." },
        { opponent: "Bulgarie", result: "W", score: "3-1", competition: "UEFA Q." },
        { opponent: "Bosnie", result: "D", score: "2-2", competition: "UEFA Q." },
        { opponent: "Irlande du N.", result: "W", score: "2-0", competition: "UEFA Q." },
        { opponent: "Norvège", result: "W", score: "3-0", competition: "UEFA Q." },
      ],
      stats: {
        possession: 57,
        goalsScored: 19,
        goalsConceded: 5,
        xGFor: 17.3,
        xGAgainst: 6.2,
        qualificationPath: "Groupe 6 UEFA — 1er (10V 1N 1D)",
        cleanSheets: 5,
      },
      lineup: {
        formation: "4-3-3",
        players: [
          { name: "Flekken", position: "GK", number: 1, flag: "🇳🇱" },
          { name: "Dumfries", position: "RB", number: 2, flag: "🇳🇱" },
          { name: "De Vrij", position: "CB", number: 3, flag: "🇳🇱" },
          { name: "Van Dijk", position: "CB", number: 4, flag: "🇳🇱" },
          { name: "Blind", position: "LB", number: 5, flag: "🇳🇱" },
          { name: "Schouten", position: "CDM", number: 6, flag: "🇳🇱" },
          { name: "De Jong F.", position: "CM", number: 21, flag: "🇳🇱" },
          { name: "Veerman", position: "CM", number: 8, flag: "🇳🇱" },
          { name: "Bergwijn", position: "RW", number: 7, flag: "🇳🇱" },
          { name: "Depay M.", position: "ST", number: 9, flag: "🇳🇱" },
          { name: "Gakpo", position: "LW", number: 11, flag: "🇳🇱" },
        ],
      },
      keyPlayers: ["Virgil van Dijk", "Frenkie de Jong", "Cody Gakpo"],
      injuries: [],
      suspensions: [],
    },
    date: "2026-06-27",
    time: "18:00",
    stadium: "BMO Field",
    city: "Toronto",
    country: "Canada",
    group: "F",
    round: "Phase de groupes",
    h2h: [
      { date: "2022-11-21", homeTeam: "Pays-Bas", awayTeam: "Sénégal", score: "2-0", competition: "Phase de groupes CDM 2022" },
      { date: "2018-10-10", homeTeam: "Sénégal", awayTeam: "Pays-Bas", score: "1-1", competition: "Match amical" },
      { date: "2002-06-01", homeTeam: "Pays-Bas", awayTeam: "Sénégal", score: "1-1", competition: "Match amical" },
      { date: "2000-06-10", homeTeam: "Sénégal", awayTeam: "Pays-Bas", score: "0-1", competition: "Match amical" },
      { date: "1998-06-15", homeTeam: "Pays-Bas", awayTeam: "Sénégal", score: "0-0", competition: "Match amical" },
    ],
    odds: [
      { bookmaker: "Winamax", home: 3.10, draw: 3.20, away: 2.20 },
      { bookmaker: "Unibet", home: 3.05, draw: 3.25, away: 2.25 },
      { bookmaker: "PMU", home: 3.15, draw: 3.15, away: 2.15 },
    ],
  },
];

export function getMatchById(id: string): Match | undefined {
  return MATCHES.find((m) => m.id === id);
}

export function getMatchesByGroup(group: string): Match[] {
  return MATCHES.filter((m) => m.group === group);
}
